name: stable

on:
  push:
    branches:
      - main

jobs:
  publish:
    concurrency:
      group: stable
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Extract version
        id: get_version
        run: echo "version=$(./gradlew properties --console=plain | grep 'version:'  | sed 's/version:\s*//g')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          prerelease: false
          body: ''
          files: ./build/libs/*-all.jar

      - name: Modrinth Release
        uses: dsx137/modrinth-releaser@main
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        with:
          name: ${{ steps.get_version.outputs.version }}
          project_id: Et53O94J
          loaders: velocity
          game_versions: 1.12.2:1.20.6
          version_number: ${{ steps.get_version.outputs.version }}
          changelog: ${{ github.event.head_commit.message }}
          version_type: beta
          files: build/libs/Memo-${{ steps.get_version.outputs.version }}-all.jar
